export const REQUEST_READ_SEARCHES = 'REQUEST_READ_SEARCHES';
export const SUCCESS_READ_SEARCHES = 'SUCCESS_READ_SEARCHES';
export const FAILURE_READ_SEARCHES = 'FAILURE_READ_SEARCHES';

export const REQUEST_CREATE_SEARCH = 'REQUEST_CREATE_SEARCH';
export const SUCCESS_CREATE_SEARCH = 'SUCCESS_CREATE_SEARCH';
export const FAILURE_CREATE_SEARCH = 'FAILURE_CREATE_SEARCH';